[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  WC_CONSUMER_KEY = "ck_b62b46d7b6d6b449fba09064520e0ef526eefbd8"
  WC_CONSUMER_SECRET = "cs_3c5568f212f76cb2a6c66f476624b7dad7d26f4c"
  WOO_STORE_URL = "https://alphaservis.hr/"