[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  # Ovdje NE SMIJE biti WC_CONSUMER_KEY i WC_CONSUMER_SECRET
  NETLIFY_DATABASE_URL = "..."
  NETLIFY_DATABASE_URL_UNPOOLED = "..."
  WOO_STORE_URL = "..."